apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: airflow
data:
  filebeat.yml: |
    filebeat.inputs:
      - type: log
        paths:
          - /opt/airflow/logs/**/*.log

    output.elasticsearch:
      hosts: ["http://elasticsearch.airflow.svc.cluster.local:9200"]
      index: "airflow-logs-%{+yyyy.MM.dd}"

