apiVersion: v1
kind: Service
metadata:
  name: airflow-web
  namespace: airflow
spec:
  selector:
    component: webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: airflow
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: webserver
  endpoints:
    - port: metrics
      interval: 30s

