prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    retention: "7d"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true


