apiVersion: v1
kind: ConfigMap
metadata:
  name: observability-portal-html
  namespace: nginx
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Portal de Observabilidade - DataMaster</title>
      <style>
        body { font-family: sans-serif; background: #f4f4f4; padding: 40px; }
        h1 { color: #333; }
        ul { list-style: none; padding: 0; }
        li { margin: 10px 0; }
        a { text-decoration: none; color: #0078d4; font-size: 18px; }
      </style>
    </head>
    <body>
      <h1>Portal de Observabilidade</h1>
      <ul>
        <li><a href="https://grafana.datamaster.internal">Grafana</a></li>
        <li><a href="https://airflow.datamaster.internal">Airflow</a></li>
        <li><a href="https://kibana.datamaster.internal">Kibana</a></li>
        <li><a href="https://spark-history.datamaster.internal">Spark History</a></li>
        <li><a href="https://dashboard.datamaster.internal">Kubernetes Dashboard</a></li>
      </ul>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: observability-portal
  namespace: nginx
spec:
  selector:
    app: observability-portal
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability-portal
  namespace: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability-portal
  template:
    metadata:
      labels:
        app: observability-portal
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          configMap:
            name: observability-portal-html

