replicaCount: 1

image:
  repository: public.ecr.aws/u3q2e8l3/spark-history-server
  tag: v3.3.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 18080

persistence:
  enabled: true
  storageClass: default
  accessMode: ReadWriteOnce
  size: 5Gi
  mountPath: /data
  existingClaim: spark-event-logs

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

