apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-history-server
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: spark-history-server
  template:
    metadata:
      labels:
        app: spark-history-server
    spec:
      containers:
        - name: spark-history-server
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 18080
          volumeMounts:
            - name: event-logs
              mountPath: {{ .Values.persistence.mountPath }}
      volumes:
        - name: event-logs
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}

