apiVersion: v1
kind: Service
metadata:
  name: spark-history-server
  namespace: spark-history
spec:
  selector:
    app: spark-history-server
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 18080
  type: {{ .Values.service.type }}

