name: Deploy HELMs Tools to AKS

on:
  push:
    branches: [ main ]
    paths:
      - iac/aks-deploy/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/aks-deploy
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Azure Login
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Set up AKS context
      uses: azure/aks-set-context@v1
      with:
        cluster-name: ${{ secrets.AKS_NAME }}
        resource-group: ${{ secrets.AKS_RG }}

    - name: Add Helm repositories
      run: |
        helm repo add apache-airflow https://airflow.apache.org
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo add elastic https://helm.elastic.co
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo add spark-operator https://googlecloudplatform.github.io/spark-on-k8s-operator
	helm repo add cloudnativeapp https://helm.cloudnativeapp.dev
        helm repo update

    - name: Deploy Helm charts
      run: |
        helm upgrade --install airflow apache-airflow/airflow \
          --namespace airflow \
          --values values/airflow.yaml

        helm upgrade --install elasticsearch elastic/elasticsearch \
          --namespace elk \
          --values values/elk.yaml

        helm upgrade --install kibana elastic/kibana \
          --namespace elk \
          --values values/elk.yaml

        helm upgrade --install grafana grafana/grafana \
          --namespace grafana \
          --values values/grafana.yaml

        helm upgrade --install prometheus prometheus-community/prometheus \
          --namespace prometheus \
          --values values/prometheus.yaml

        helm upgrade --install nginx ingress-nginx/ingress-nginx \
          --namespace nginx \
          --values values/nginx.yaml
        
        helm install spark-operator/spark-operator --namespace spark-operator \
           --set webhook.enable=true --set sparkJobNamespace=spark

	helm install spark-history cloudnativeapp/spark-history-server \
	  --namespace spark-history \
	  --set persistence.enabled=true \
	  --set persistence.existingClaim=spark-event-logs \
	  --set spark.history.fs.logDirectory=file:/data \
	  --set service.type=ClusterIP

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f manifests/secrets/
        kubectl apply -f manifests/controllers/
        kubectl apply -f manifests/ingress/
        kubectl apply -f manifests/pvc/
        

