name: Deploy Azure Functions

on:
  push:
    paths:
      - app/azure_functions/**
    branches:
      - main

jobs:
  deploy-functions:
    runs-on: ubuntu-latest

    env:
      PYTHON_VERSION: '3.10'
      FUNCTION_LIST: |
        finance_csv_ingestor
        news_producer

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Azure Login
        run: |
          az login --service-principal \
            -u ${{ secrets.AZURE_CLIENT_ID }} \
            -p ${{ secrets.AZURE_CLIENT_SECRET }} \
            --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Parse AZURE_CREDENTIALS JSON
        run: |
          echo '${{ secrets.AZURE_CREDENTIALS }}' > azure_credentials.json
          echo "ARM_CLIENT_ID=$(jq -r .clientId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(jq -r .clientSecret azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(jq -r .subscriptionId azure_credentials.json)" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(jq -r .tenantId azure_credentials.json)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pytest

      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Deploy Functions Sequentially
        run: |
          for FUNC in $FUNCTION_LIST; do
            echo "Deploying function: $FUNC"

            echo "Format code"
            black app/azure_functions/$FUNC

            echo "Install dependencies"
            pip install -r app/azure_functions/$FUNC/requirements.txt

            echo "Run unit tests"
            pytest app/azure_functions/$FUNC --maxfail=1 --disable-warnings --exitfirst

            NORMALIZED_NAME=$(echo "$FUNC" | sed 's/_/-/g')-func1
            echo "Normalized name: $NORMALIZED_NAME"

            echo "Obtendo credenciais de publicação..."
            az functionapp deployment list-publishing-profiles \
              --name $NORMALIZED_NAME \
              --resource-group ${{ secrets.RSG }} \
              --output tsv > profile.txt

            SCM_URL=$(grep -m1 'scm.azurewebsites.net' profile.txt | cut -f10)
            USER=$(grep -m1 'scm.azurewebsites.net' profile.txt | cut -f11)
            PASS=$(grep -m1 'scm.azurewebsites.net' profile.txt | cut -f12)

            echo "Parando a Function App..."
            az functionapp stop --name $NORMALIZED_NAME --resource-group ${{ secrets.RSG }} || true

            #echo "Limpando arquivos antigos da Function App..."
            #curl -sk -X DELETE "https://$SCM_URL/api/vfs/site/wwwroot/" \
            #  -H "If-Match: *" \
            #  -u "$USER:$PASS" || true

            echo "Deploying with Azure Functions Core Tools..."
            cd app/azure_functions/$FUNC
            func azure functionapp publish $NORMALIZED_NAME --python
            cd -

            echo "Iniciando a Function App..."
            az functionapp start --name $NORMALIZED_NAME --resource-group ${{ secrets.RSG }} || true
            sleep 30
          done

