name: Terraform CI-CD

on:
  push:
    paths:
      - iac/infra/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/infra

    environment: production

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get secrets from Key Vault
      run: |
        export TF_SP_SECRET=$(az keyvault secret show \
          --name spn-client-secret \
          --vault-name kv-secret-datamastermdl \
          --query value -o tsv)

        echo "TF_SP_SECRET=$TF_SP_SECRET" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.13.1

    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Format Check
      run: terraform fmt -check

    - name: Download Terraform State
      uses: actions/download-artifact@v4
      with:
        name: terraform-state
        path: iac/infra/
      continue-on-error: true

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      env:
        ARM_CLIENT_SECRET: ${{ env.TF_SP_SECRET }}
 
    - name: Upload Terraform State
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: iac/infra/terraform.tfstate
 
