name: Terraform CI-CD

on:
  push:
    paths:
      - iac/infra/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: iac/infra

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Azure Login
      run: |
        az login --service-principal \
          -u ${{ secrets.AZURE_CLIENT_ID }} \
          -p ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get secrets from Key Vault
      run: |
        export TF_SP_SECRET=$(az keyvault secret show \
          --name terraform-client-secret \
          --vault-name kv-secrets-datamastermdl \
          --query value -o tsv)

        echo "TF_SP_SECRET=$TF_SP_SECRET" >> $GITHUB_ENV

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Init
      run: terraform init -upgrade

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        ARM_CLIENT_SECRET: ${{ env.TF_SP_SECRET }}

